/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HighTicketSemCallRouteImport } from './routes/high-ticket-sem-call'
import { Route as IndexRouteImport } from './routes/index'

const HighTicketSemCallRoute = HighTicketSemCallRouteImport.update({
  id: '/high-ticket-sem-call',
  path: '/high-ticket-sem-call',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/high-ticket-sem-call': typeof HighTicketSemCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/high-ticket-sem-call': typeof HighTicketSemCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/high-ticket-sem-call': typeof HighTicketSemCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/high-ticket-sem-call'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/high-ticket-sem-call'
  id: '__root__' | '/' | '/high-ticket-sem-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HighTicketSemCallRoute: typeof HighTicketSemCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/high-ticket-sem-call': {
      id: '/high-ticket-sem-call'
      path: '/high-ticket-sem-call'
      fullPath: '/high-ticket-sem-call'
      preLoaderRoute: typeof HighTicketSemCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HighTicketSemCallRoute: HighTicketSemCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
